# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 16:44
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyWeightLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Dibuat')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tanggal')),
                ('max_weight', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Berat Maksimum')),
                ('min_weight', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Berat Minimum')),
            ],
        ),
    ]
